version: 2
updates:
  # Keep bundler dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "01:00"
      timezone: "Asia/Seoul"
    groups:
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@nestjs/*"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@nestjs/*"
      nestjs:
        patterns:
          - "@nestjs/*"
